# Generated by Django 3.2.5 on 2021-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('key', models.CharField(max_length=40)),
                ('value', models.FloatField()),
            ],
        ),
    ]
